INSERT INTO AIRCRAFT_SPECIFICATIONS (SPEZIFICATION_ID, STRUCTURE, FUEL_TANK_CAPACITY,
                                     MIN_SPEED, MAX_SPEED, MAX_ALTITUDE, SPECIFICATION_CODE) VALUES (1, 3, 10, 2, 6, 5, 'Tunderbolt');
INSERT INTO AIRCRAFT_SPECIFICATIONS (SPEZIFICATION_ID, STRUCTURE, FUEL_TANK_CAPACITY,
                                     MIN_SPEED, MAX_SPEED, MAX_ALTITUDE, SPECIFICATION_CODE) VALUES (2, 2, 8, 3, 8, 4, 'Vulture');
INSERT INTO AIRCRAFTS (AIRCRAFT_ID, ALTITUDE, FUEL, NAME, SpecificationId, SPEED) VALUES (1, 5, 6,
                                                                                           'Executioner', 1, 4);
INSERT INTO AIRCRAFTS (AIRCRAFT_ID, ALTITUDE, FUEL, NAME, SpecificationId, SPEED) VALUES (2, 3, 3,
                                                                                           'Dakkajet', 2, 3);
INSERT INTO MERCENARIES (MERCENARY_ID, BODY_SKILLS, COMBAT_SKILLS, FIRST_NAME, LAST_NAME) VALUES
    (1, 4, 4, 'Han', 'Solo');
INSERT INTO MERCENARIES (MERCENARY_ID, BODY_SKILLS, COMBAT_SKILLS, FIRST_NAME, LAST_NAME) VALUES
    (2, 8, 8, 'Luke', 'Skywalker');
INSERT INTO COMPARTMENTS (COMPARTMENT_ID, AIRCRAFTID, NAME) VALUES (1, 1, 'pilot cockpit');
INSERT INTO COMPARTMENTS (COMPARTMENT_ID, AIRCRAFTID, NAME) VALUES (2, 1, 'storage compartment');
INSERT INTO COMPARTMENTS (COMPARTMENT_ID, AIRCRAFTID, NAME) VALUES (3, 1, 'machine room');
INSERT INTO COMPARTMENTS (COMPARTMENT_ID, AIRCRAFTID, NAME) VALUES (4, 1, 'weapon compartment
rear');
INSERT INTO CRIME_SYNDICATES (SYNDICATE_ID, NAME, LOCATION) VALUES (1, 'Black Vipers', 'New York, USA');
INSERT INTO CRIME_SYNDICATES (SYNDICATE_ID, NAME, LOCATION) VALUES (2, 'Red Scorpions', 'Los Angeles, USA');
INSERT INTO CRIME_SYNDICATES (SYNDICATE_ID, NAME, LOCATION) VALUES (3, 'Golden Dragons', 'Shanghai, China');
INSERT INTO CRIME_SYNDICATES (SYNDICATE_ID, NAME, LOCATION) VALUES (4, 'Shadow Panthers', 'London, UK');
INSERT INTO CRIME_SYNDICATES (SYNDICATE_ID, NAME, LOCATION) VALUES (5, 'Iron Fangs', 'Moscow, Russia');