USE CrimesDB;

-- Insert into AIRCRAFT_SPEZIFICATIONS
INSERT INTO AIRCRAFT_SPECIFICATIONS (SPEZIFICATION_ID, STRUCTURE, FUEL_TANK_CAPACITY, MIN_SPEED, MAX_SPEED, MAX_ALTITUDE, SPECIFICATION_CODE)
VALUES (1, 100, 500, 150, 900, 30000, 'SPZ001');

-- Insert into CRIME_SYNDICATES
INSERT INTO CRIME_SYNDICATES (SYNDICATE_ID, NAME, LOCATION)
VALUES (1, 'Black Ravens', 'Unknown');

-- Insert into MERCENARIES
USE CrimesDB;
INSERT INTO MERCENARIES (MERCENARY_ID, FIRST_NAME, LAST_NAME, BODY_SKILLS, COMBAT_SKILLS)
VALUES (1, 'John', 'Doe', 80, 90);

-- Insert into MERCENARY_REPUTATIONS
USE CrimesDB;
INSERT INTO MERCENARY_REPUTATIONS (SYNDICATE_ID, MERCENARY_ID, REPUTATION_CHANGE)
VALUES (1, 1, 'Increased');

-- Insert into AIRCRAFTS
USE CrimesDB;
INSERT INTO AIRCRAFTS (AIRCRAFT_ID, SpecificationId, FUEL, SPEED, ALTITUDE, NAME)
VALUES (1, 1, 300, 700, 25000, 'Black Hawk');

-- Insert into COMPARTMENTS
INSERT INTO COMPARTMENTS (COMPARTMENT_ID, AircraftId, NAME)
VALUES (1, 1, 'Black Hawk');

-- Insert into MACHINERIES
USE CrimesDB;
INSERT INTO MACHINERIES (MACHINERY_ID, LABEL, FUNCTION, COMPARTMENT_ID)
VALUES (1, 'Engine X1', 'Propulsion', 1);

-- Insert into WEAPONS
INSERT INTO WEAPONS (MACHINERY_ID)
VALUES (1);

-- Insert into ENERY_SYSTEMS
INSERT INTO ENERGY_SYSTEMS (MACHINERY_ID)
VALUES (1);

-- Insert into ENVIRONMENTAL_SYSTEMS
INSERT INTO ENVIRONMENTAL_SYSTEMS (MACHINERY_ID)
VALUES (1);

-- Insert into AIRCRAFT_CREW_JT
USE CrimesDB;
INSERT INTO AIRCRAFT_CREW_JT (AIRCRAFT_ID, MERCENARY_ID, JOINED_AT)
VALUES (1, 1, '2025-03-10');
